version: "3.8"

services:
    mc:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./:/app
        tty: true
        stdin_open: true
        restart: unless-stopped
        command:
            [
                "python3",
                "launch-server.py",
                "fabric-server-mc.1.20.1-loader.0.16.10-launcher.1.0.1.jar",
            ]
        stop_grace_period: 300s
        network_mode: "service:zerotier" # Connect the Minecraft container to the ZeroTier network
        depends_on:
            - zerotier # Ensure ZeroTier container is running before Minecraft

    zerotier:
        image: zerotier/zerotier:latest
        container_name: zerotier-client
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun:/dev/net/tun
        volumes:
            - ./zeroTierConfig:/var/lib/zerotier-one
        command: <Your network ID>
        restart: unless-stopped
